# Generated by Django 5.1 on 2024-09-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('author', models.CharField(max_length=120)),
                ('up', models.IntegerField(default=0)),
                ('down', models.IntegerField(default=0)),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
