# Generated by Django 3.2.11 on 2025-06-23 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='游戏名称')),
                ('platform', models.CharField(max_length=50, verbose_name='平台')),
                ('release_date', models.DateField(verbose_name='发行日期')),
                ('meta_reviews_number', models.PositiveIntegerField(default=0, verbose_name='Meta评价数量')),
                ('meta_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Meta评分')),
                ('meta_positive', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Meta好评率(%)')),
                ('meta_mixed', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Meta中立评价率(%)')),
                ('meta_negative', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Meta差评率(%)')),
                ('user_reviews_number', models.PositiveIntegerField(default=0, verbose_name='用户评价数量')),
                ('user_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='用户评分')),
                ('user_positive', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='用户好评率(%)')),
                ('user_mixed', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='用户中立评价率(%)')),
                ('user_negative', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='用户差评率(%)')),
                ('developer', models.CharField(blank=True, max_length=100, verbose_name='开发商')),
                ('publisher', models.CharField(blank=True, max_length=100, verbose_name='发行商')),
                ('genres', models.TextField(verbose_name='游戏类型')),
                ('image_url', models.CharField(max_length=120, verbose_name='图片链接')),
                ('information', models.TextField(verbose_name='游戏简介')),
                ('review_user', models.TextField(blank=True, default='[]', null=True, verbose_name='评价用户')),
            ],
            options={
                'verbose_name': '游戏',
                'verbose_name_plural': '游戏列表',
            },
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['name'], name='game_game_name_ef2ba8_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['meta_score', 'user_score'], name='game_game_meta_sc_da19b7_idx'),
        ),
    ]
