# Generated by Django 3.2.11 on 2025-06-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20250623_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='chinese_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='中文名'),
        ),
    ]
