# Generated by Django 3.2.11 on 2025-06-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_chinese_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image_url',
            field=models.CharField(max_length=500, verbose_name='图片链接'),
        ),
    ]
