# Generated by Django 3.2.11 on 2025-06-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_game_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image_url',
            field=models.TextField(verbose_name='图片链接'),
        ),
    ]
