# Generated by Django 3.2.11 on 2025-06-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_game_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='review_user',
            field=models.TextField(blank=True, default='{}', null=True, verbose_name='评价用户'),
        ),
    ]
